[mongodb]
mongodb-dev.rebba.online

[catalogue]
catalogue-dev.rebba.online

[redis]
redis-dev.rebba.online

[user]
user-dev.rebba.online

[cart]
cart-dev.rebba.online

[mysql]
mysql-dev.rebba.online

[shipping]
shipping-dev.rebba.online

[rabbitmq]
rabbitmq-dev.rebba.online

[payment]
payment-dev.rebba.online

[frontend]
frontend-dev.rebba.online


[all:vars]
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.rebba.online
CATALOGUE_HOST=catalogue-dev.rebba.online
CART_HOST=cart-dev.rebba.online
MYSQL_HOST=mysql-dev.rebba.online



