- name: create Ec2 instance and R53 records
  hosts: local
  connection: local
  vars:
    AMI_ID: ami-0220d79f3f480ecf5
    SG_ID: sg-0c2d3e7831a625405
    ENV: dev
    instances:
     - mongodb
     - catalogue
  tasks:
    - name: create ec2 instance
      amazon.aws.ec2_instance:
       instance_type: "t3.micro"
       security_group: "{{ SG_ID }}"
       image_id: "{{ AMI_ID }}"
       name: "{{ item }}-{{ ENV }}" #mongodb-dev
       tags :
         Project: roboshop
         Component: "{{ item }}"
         Environment: "{{ ENV }}"
         Name: "{{ item }}-{{ ENV }}"
      loop: "{{ instances }}"
      register: ec2_output
- name: prints the output of ec2
  ansible.builtin.debug:
    msg: "{{ ec2_output }}"