- name: configure the shipping service
  hosts: shipping
  become: yes
  tasks:
    - name: install maven
      ansible.builtin.dnf:
       name: '{{ item }}'
       state: present
      loop:
      - maven
      - mysql

    - name: creating system user
      ansible.builtin.user:
       system: true
       name: roboshop
       comment: roboshop system user
       home: /app
       shell: /sbin/nologin
  
    - name: Creating app directory
      ansible.builtin.file:
       path: /app
       state: directory

    - name: Delete the existing app directory
      ansible.builtin.file:
       path: /app
       state: absent
  
    - name: Downloading the code file
      ansible.builtin.get_url:
       url: https://roboshop-artifacts.s3.amazonaws.com/shipping-v3.zip
       dest: /tmp/shipping.zip

    - name: unzipping the shipping code
      ansible.builtin.unarchive:
       src: /tmp/payment.zip
       dest: /app
       
    
    - name: installing dependencies
      ansible.builtin.command: mvn clean package
      args:
        chdir: /app

    - name: rename the file
      ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
      args:
        chdir: /app
  
    - name: Copying the shipping.service file
      ansible.builtin.template:
       src: shipping.service
       dest: /etc/systemd/system/shipping.service
      
    - name: Restart the service
      ansible.builtin.systemd_service:
       daemon_reload: true

    - name: Installing python dependencies
      ansible.builtin.pip:
       name: "{{ item }}"
       executable: pip3.9
      loop:
       - cryptography
       - PyMySQL

    - name: import shipping data
      community.mysql.mysql_db:
       state: import
       name: all
       login_host: "{{ MYSQL_HOST }}"
       login_user: root
       login_password: RoboShop@1
       target: "{{ item }}"
      loop:
       - /app/db/schema.sql
       - /app/db/app-user.sql 
       - /app/db/master-data.sql

    - name: start and enable  shipping
      ansible.builtin.service:
       name: shipping
       state: restarted
       enabled: yes
